### ISSUE TITLE
Firefox 74.0

### ISSUE THREAD

**Issue by cag014** [spenibus/cors-everywhere-firefox-addon#32] opened 2020-03-11 15:07 UTC
Doesn't work on new 74.xxx release.
Please help

**Comment by spenibus** [comment] 2020-03-11 20:34
Just checked [cors-everywhere-test][1] using Firefox 74.0 and it works. Gonna need more info.

> waiting for xmlHttpRequest
> readyState: 2 status: 200
> readyState: 3 status: 200
> readyState: 4 status: 200


[1]: http://spenibus.net/cors-everywhere-test.html

**Comment by cag014** [comment] 2020-03-11 21:08
Monitoring network I do receive status 200, but no response in my java-script  and on console there is an error:
 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hc3-00000138.local/api/globalVariables/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Here is the code in java-script (very simple)
           **var xhr = new XMLHttpRequest(); xhr.withCredentials = true;
           xhr.open("GET",uri,true); 
            xhr.send();**
See attachments.

<img width="542" alt="Capture" src="https://user-images.githubusercontent.com/45340622/76463900-ec882b00-63ec-11ea-8576-0a1ae837732b.PNG">
<img width="536" alt="Capture1" src="https://user-images.githubusercontent.com/45340622/76463904-edb95800-63ec-11ea-83e4-72d5f5c39170.PNG">
.

**Comment by cag014** [comment] 2020-03-11 21:53
By the way have copied your test code and run it ... doesn't work either!? 
What I'm doing wrong?

<img width="888" alt="Capture" src="https://user-images.githubusercontent.com/45340622/76467962-7affab00-63f3-11ea-8223-279d11da04f6.PNG">

**Comment by spenibus** [comment] 2020-03-11 22:36
Could be a mixed protocol issue when calling http:// from file:///. Sounds like the kind of thing they would block.

**Comment by cag014** [comment] 2020-03-11 22:40
Any workaround for that?
Thanks

**Comment by spenibus** [comment] 2020-03-11 22:47
No idea at this point.

Since the addon doesn't really disable CORS but only spoofs the requests to make them look legit, anything that is disallowed by design is likely impossible to break. Advanced settings have to be investigated but I wouldn't expect much, considering they never bothered to offer a switch to disable security measures in the first place.

**Comment by cag014** [comment] 2020-03-11 23:03
OK.
Thank you for your time... back to Chrome

**Comment by cag014** [comment] 2020-03-11 23:48
You're absolutely correct... Firefox blocks file://
Have run this files via my router and it works now.
Thanks for a tip.

**Comment by slideroh** [comment] 2020-03-12 20:07
Hello,
Let me add my two cents.

Since new update to Firefox 74.0 I have a problem with two things:
Reason: CORS header 'Access-Control-Allow-Origin' missing
(https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)
and
Reason: CORS request did not succeed
(https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed)

This is when I use my file:// version of the site, however my online version works fine - there is no problem with CORS. Looks like Firefox blocks somehow file:// connected with http/s since 74.0.

**Comment by spenibus** [comment] 2020-03-13 19:36
Looks like the header injection just stops working in local mode. I fear there isn't much to do about it.

**Comment by cag014** [comment] 2020-03-14 14:59
Thank for checking out the problem...
Hope Firefox will reverse this decision on next release

**Comment by spenibus** [comment] 2020-03-14 20:18
That's very optimistic considering what Mozilla has been doing in recent years.

**Comment by maheee** [comment] 2020-03-15 19:44
mhm, I have a similar addon, it's the same.
FF just doesn't call the handlers 'onBeforeSendHeaders' and 'onHeadersReceived' on local pages (file:///) anymore.

**Comment by cag014** [comment] 2020-03-19 23:12
I'm unable to find CORS everywhere add-on for mobile!?
Am I missing something?

**Comment by spenibus** [comment] 2020-03-19 23:17
Untested on mobile so not officially available. You can probably force the install though, can't remember having ever tried. See #15.

**Comment by Bluscream** [comment] 2020-04-15 07:11
![image](https://user-images.githubusercontent.com/3318223/79308581-1e634480-7ef9-11ea-8ff0-73ef2e0a4e2b.png)

**Comment by spenibus** [comment] 2020-04-15 18:19
Just tried with Firefox 75 and the online test still works.
![screenshot-20200415-201533-006912](https://user-images.githubusercontent.com/7434018/79372776-564ca500-7f56-11ea-9a49-0be358980c19.png)

**Comment by cag014** [comment] 2020-04-15 18:46
Wow, yes it works... so they did it.
Thanks for notification

**Comment by Bluscream** [comment] 2020-04-15 22:01
@spenibus why does it work for you? Is there some setting i need to adjust?

**Comment by cag014** [comment] 2020-04-15 22:14
Yes, it again works from local file.. I thought that was your message for, isn't?

**Comment by spenibus** [comment] 2020-04-15 22:46
@Bluscream It should work right away when green, at least for my basic test. Maybe something else is blocking the url.

@cag014 Didn't even test local, I saw the online version in the screenshot and tried that. But yes indeed actually, it does work now.

![screenshot-20200416-004134-006918](https://user-images.githubusercontent.com/7434018/79396023-4abfa500-7f7b-11ea-9898-0340ac572cb2.png)

**Comment by spenibus** [comment] 2020-04-19 21:47
Closing this based on seemingly fixed behaviour in 75.0.

**Closed as completed by spenibus** 2020-04-19 21:47 UTC

**Comment by cag014** [comment] 2020-04-19 22:03
OK. thanks for your support

**Comment by Bluscream** [comment] 2020-04-20 03:52
It still does not work, same version

**Comment by spenibus** [comment] 2020-04-20 16:29
@Bluscream Open the console (F12), refresh the page and copy the logs.

**Comment by Bluscream** [comment] 2020-04-21 04:12
You mean this?

```
GEThttp://spenibus.net/cors-everywhere-test.html
[HTTP/1.1 200 OK 50ms]

GEThttp://spenibus.net/style.css
[HTTP/1.1 200 OK 29ms]

GEThttp://spenibus.net/favicon.ico
[HTTP/1.1 200 OK 26ms]

Unknown property ‘-moz-border-radius’.  Declaration dropped. cors-everywhere-test.html:22:24
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://google.com/. (Reason: CORS request did not succeed).
Requesting https://www.google.com/s2/favicons?domain=github.com Add Favicons to links.user.js:33:25
Requesting https://www.google.com/s2/favicons?domain=gitlab.com Add Favicons to links.user.js:33:25
GEThttps://github.com/DEMENT0R/steam_activation_button/raw/master/key.png
[HTTP/1.1 302 Found 25ms]

GEThttps://github.com/DEMENT0R/steam_activation_button/raw/master/list.png
[HTTP/1.1 302 Found 32ms]

GEThttps://www.google.com/s2/favicons?domain=github.com
[HTTP/2 200 OK 20ms]

GEThttps://www.google.com/s2/favicons?domain=gitlab.com
[HTTP/2 200 OK 19ms]

GEThttps://raw.githubusercontent.com/DEMENT0R/steam_activation_button/master/key.png
[HTTP/1.1 200 OK 171ms]

GEThttps://raw.githubusercontent.com/DEMENT0R/steam_activation_button/master/list.png
[HTTP/1.1 200 OK 171ms]

```
waiting for xmlHttpRequest readyState: 4
status: 0

**Comment by spenibus** [comment] 2020-04-21 22:36
Error should be:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://google.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Can you access [http://google.com](http://google.com) normally ?

I've updated the test page, you can try other urls.
